language: c

# XXX: Travis doesn't allow libnewlib-arm-none-eabi to be installed yet
sudo: required

dist: trusty

env:
  global:
   - TOOLKIT_PATH=.
   - SOURCES=test/main.c
  matrix:
   - MCU=LPC11U24_301
   - MCU=EFM32LG990F256

addons:
  apt:
    packages:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi

script:
  - make --file=makefile.mk
